print("Titel:", "Het is al laat toch")
print("Artiest:", "Racoon")

print("[Verse 1]")
print("Wat een idee, wat een plan oh verdomme man")
print("Waarom ben ik zo nerveus")
print("Ga naar binnen, ga toch zitten en wat drinken dan")
print("Misschien vindt ze je wel leuk")
print("En jij haar, dus elkaar en je kan een beetje lachen daar")
print("Er is altijd een keus")
print("De sfeer wordt plots zo serieus")


print("[Chorus]")
print("Het is al laat toch")
print("Het is al laat toch")
print("Wat doen we hier nog")
print("Het is al laat toch")
print("Het is al laat toch")
print("Wil jij je bier nog")
print("Kom dan gaan we naar mijn huis")

print("[Verse 2]")
print("Ik snap het niet, 't was zo mooi, niet normaal meer, allemaal")
print("Wat kan de tijd toch snel kapot")
print("Heel het leven op de schop, opzoek naar een droomverhaal")
print("En ik zoek mee en voel me rot")
print("Ben ik het kwijt, of heb ik het ergens laten liggen dan")
print("Vertel me even waar")
print("We groeien door voor zover je dat zo noemen kan")
print("We groeien verder uit elkaar")

print("[Chorus]")
print("Het is al laat toch")
print("Het is al laat toch")
print("Wat doen we hier nog")
print("Het is al laat toch")
print("Het is al laat toch")
print("Blijf jj maar hier nog")
print("Dan ga ik alvast naar huis")

print("[Bridge]")
print("Nu de deur is dicht gevallen")
print("Jouw aanwezigheid verdwijnt")
print("Wordt mijn wereld enkel kleiner")
print("Zielsalleen door koppigheid")
print("Wat we vergeten bij het schelden")
print("Op de sleur van zoveel jaar")
print("Dat we zeuren, dat we zeiken")
print("Maar wel in de zelfde taal")

print("[Chorus]")
print("Het is al laat toch")
print("Het is al laat toch")
print("Wat doen we hier nog")
print("Kom dan gaan we naar mijn huis")

print("[Chorus]")
print("Het is al laat toch")
print("Het is al laat toch")
print("Wat doen we hier nog")
print("Het is al laat toch")
print("Het is al laat toch")
print("Dus drink je bier op")
print("En dan gaan we naar ons huis")
